import {
  Blocks,
  BrainCircuit,
  Cloud,
  Code2,
  Crosshair,
  Database,
  Settings2,
} from "lucide-react";

export const skillGroups = [
  {
    id: "languages",
    title: "Programming Languages",
    description: "Languages I use to build software and intelligent systems.",
    icon: Code2,
    tone: "blue",
    className: "left-[31%] top-[5%] w-[21rem]",
    shape: "rounded-[26%_18%_24%_15%/18%_24%_20%_28%]",
    skills: ["Python", "JavaScript", "TypeScript", "Java", "C++/C", "C#"],
  },

  {
    id: "ai",
    title: "AI / ML",
    description: "Techniques and models for building intelligent applications.",
    icon: BrainCircuit,
    tone: "red",
    className: "left-[63.5%] top-[7%] w-[22rem]",
    shape: "rounded-[18%_25%_18%_26%/24%_18%_25%_18%]",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Generative AI",
      "LLMs",
      "NLP",
      "Transformers",
      "RAG",
    ],
  },

  {
    id: "frameworks",
    title: "Frameworks & Libraries",
    description: "Frameworks I use to turn ideas into working applications.",
    icon: Blocks,
    tone: "red",
    className: "left-[25.5%] top-[31%] w-[22rem]",
    shape: "rounded-[18%_23%_21%_27%/25%_18%_27%_20%]",
    skills: [
      "LangChain",
      "LangGraph",
      "FastAPI",
      "React",
      "Next.js",
      "Node.js",
      "Celery",
      "Scikit-learn",
      "Pandas",
    ],
  },

  {
    id: "databases",
    title: "Databases & Storage",
    description: "Working with structured data and high-context retrieval.",
    icon: Database,
    tone: "blue",
    className: "left-[77.5%] top-[34%] w-[20rem]",
    shape: "rounded-[25%_16%_24%_17%/19%_27%_18%_25%]",
    skills: [
      "Supabase",
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "SQL Server",
      "Redis",
      "Vector Databases",
      "pgvector",
    ],
  },

  {
    id: "domains",
    title: "Domains & Specialties",
    description: "Problem spaces I build and experiment in.",
    icon: Crosshair,
    tone: "blue",
    className: "left-[29%] top-[59%] w-[22rem]",
    shape: "rounded-[22%_27%_17%_24%/18%_23%_25%_20%]",
    skills: [
      "Agentic AI",
      "AI Agents",
      "Computer Vision",
      "Voice AI",
      "Information Retrieval",
      "Parallel Computing",
      "Game Development",
    ],
  },

  {
    id: "devops",
    title: "DevOps, Cloud & Observability",
    description: "Deploying, monitoring and maintaining production systems.",
    icon: Cloud,
    tone: "red",
    className: "left-[75%] top-[61%] w-[21rem]",
    shape: "rounded-[24%_18%_27%_16%/18%_25%_19%_27%]",
    skills: [
      "Docker",
      "AWS",
      "CI/CD",
      "GitHub Actions",
      "Linux",
      "MLflow",
      "Prometheus",
      "Grafana",
      "Alertmanager",
    ],
  },
];