import {
  Blocks,
  BrainCircuit,
  Cloud,
  Code2,
  Crosshair,
  Database,
  Settings2,
} from "lucide-react";

export const skillGroups = [
  {
    id: "languages",
    title: "Programming Languages",
    description: "Languages I use to turn ideas into reliable systems.",
    icon: Code2,
    tone: "blue",
    className: "left-[31%] top-[5%] w-[21rem]",
    shape: "rounded-[26%_18%_24%_15%/18%_24%_20%_28%]",
    skills: ["Python", "JavaScript", "Java", "C++", "C", "C#"],
  },
  {
    id: "ai",
    title: "AI & ML",
    description: "Models, pipelines and tools for building intelligent systems.",
    icon: BrainCircuit,
    tone: "red",
    className: "left-[63.5%] top-[7%] w-[22rem]",
    shape: "rounded-[18%_25%_18%_26%/24%_18%_25%_18%]",
    skills: ["Machine Learning", "Deep Learning", "NLP", "Gen AI", "PyTorch", "RAG"],
  },
  {
    id: "frameworks",
    title: "Frameworks & Libraries",
    description: "Core frameworks I work with across different domains.",
    icon: Blocks,
    tone: "red",
    className: "left-[25.5%] top-[31%] w-[22rem]",
    shape: "rounded-[18%_23%_21%_27%/25%_18%_27%_20%]",
    skills: ["React", "Next.js", "Node.js", "TensorFlow", "Scikit-learn", "Pandas"],
  },
  {
    id: "databases",
    title: "Databases & Storage",
    description: "Storing, retrieving and working with production data.",
    icon: Database,
    tone: "blue",
    className: "left-[77.5%] top-[34%] w-[20rem]",
    shape: "rounded-[25%_16%_24%_17%/19%_27%_18%_25%]",
    skills: ["PostgreSQL", "MongoDB", "MySQL", "SQL Server"],
  },
  {
    id: "domains",
    title: "Domains & Specialties",
    description: "Problem spaces I enjoy exploring and building in.",
    icon: Crosshair,
    tone: "blue",
    className: "left-[29%] top-[59%] w-[22rem]",
    shape: "rounded-[22%_27%_17%_24%/18%_23%_25%_20%]",
    skills: ["Agentic AI", "RAG", "Computer Vision", "NLP", "Game Dev", "Parallel Computing"],
  },
  {
    id: "tools",
    title: "Tools & Others",
    description: "Everything else that keeps the work productive.",
    icon: Settings2,
    tone: "blue",
    className: "left-[54.5%] top-[72%] w-[20rem]",
    shape: "rounded-[18%_24%_20%_26%/24%_18%_27%_17%]",
    skills: ["Git", "VS Code", "Jupyter", "Postman", "FastAPI", "Flask"],
  },
  {
    id: "devops",
    title: "DevOps & Cloud",
    description: "Deploying, tracking and maintaining dependable systems.",
    icon: Cloud,
    tone: "red",
    className: "left-[75%] top-[61%] w-[21rem]",
    shape: "rounded-[24%_18%_27%_16%/18%_25%_19%_27%]",
    skills: ["Docker", "GitHub", "MLflow", "REST APIs", "Postman"],
  },
];
